version: "3.3"

services:
  mariadb:
    container_name: inception_mariadb
    build:
      context: ./mariadb
      dockerfile: mariadb.dockerfile
    restart: always
    env_file:
      - mariadb/.mariadb.env
    volumes:
      - ./mariadb/data:/data
    networks:
      - net

  nginx:
    container_name: inception_nginx
    depends_on:
      - php-fpm
      - mariadb
      - mkdocs
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - 443:443
    volumes:
      - ./wordpress:/var/www/html
      - ./tetris:/var/www/html/tetris
    networks:
      - net

  php-fpm:
    container_name: inception_php-fpm
    depends_on:
      - redis
      - mariadb
    build:
      context: ./php-fpm
      dockerfile: php-fpm.dockerfile
    restart: always
    env_file:
      - php-fpm/.php-fpm.env
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - net

  redis:
    container_name: inception_redis
    depends_on:
      - mariadb
    build:
      context: ./redis
      dockerfile: redis.dockerfile
    restart: always
    networks:
      - net

  mkdocs:
    container_name: inception_mkdocs
    build:
      context: ./mkdocs
      dockerfile: mkdocs.dockerfile
    volumes:
      - ./wordpress/site:/resume/site
    networks:
      - net

  ftp:
    container_name: inception_ftp
    depends_on:
      - php-fpm
    build:
      context: ./ftp
      dockerfile: ftp.dockerfile
    restart: always
    env_file:
      - ftp/.ftp.env
    volumes:
      - ./wordpress:/wordpress
    networks:
      - net

networks:
  net:
    driver: bridge
